// ============================================================================
// Marketing Pages — Barrel Export
// All page-level components for the Marketing module
// ============================================================================

export { MarketingDashboardPage } from './marketing-dashboard-page';
export { LeadsPage } from './leads-page';
export { LeadDetailPage } from './lead-detail-page';
export { LeadFormPage } from './lead-form-page';
export { ContactsPage } from './contacts-page';
export { ContactDetailPage } from './contact-detail-page';
export { ContactFormPage } from './contact-form-page';
export { CampaignsPage } from './campaigns-page';
export { CampaignBuilderPage } from './campaign-builder-page';
export { EmailBuilderPage } from './email-builder-page';
export { SmsCampaignsPage } from './sms-campaigns-page';
export { WhatsappCampaignsPage } from './whatsapp-campaigns-page';
export { SocialCalendarPage } from './social-calendar-page';
export { PostBuilderPage } from './post-builder-page';
export { AudienceSegmentsPage } from './audience-segments-page';
export { SegmentBuilderPage } from './segment-builder-page';
export { JourneysPage } from './journeys-page';
export { JourneyBuilderPage } from './journey-builder-page';
export { JourneyTemplatesPage } from './journey-templates-page';
export { LeadScoringPage } from './lead-scoring-page';
export { LeadStagesPage } from './lead-stages-page';
export { WorkflowsPage } from './workflows-page';
export { WorkflowBuilderPage } from './workflow-builder-page';
export { PlannerPage } from './planner-page';
export { PlanDetailPage } from './plan-detail-page';
export { PlanFormPage } from './plan-form-page';
export { EcommerceDashboardPage } from './ecommerce-dashboard-page';
export { AbandonedCartsPage } from './abandoned-carts-page';
export { PurchaseFollowupsPage } from './purchase-followups-page';
export { ProductCampaignsPage } from './product-campaigns-page';
export { AnalyticsOverviewPage } from './analytics-overview-page';
export { AdPerformancePage } from './ad-performance-page';
export { AttributionPage } from './attribution-page';
export { WebAnalyticsPage } from './web-analytics-page';
export { SmartUrlsPage } from './smart-urls-page';
export { GoalTrackingPage } from './goal-tracking-page';
export { EmailTemplatesPage } from './email-templates-page';
export { EmailTemplateBuilderPage } from './email-template-builder-page';
export { ABTestingPage } from './ab-testing-page';
export { RetentionPage } from './retention-page';
export { LoyaltyPage } from './loyalty-page';
export { ReferralPage } from './referral-page';
export { ContentApprovalPage } from './content-approval-page';
export { AiGrowthIntelligencePage } from './ai-growth-intelligence-page';
export { CrmSyncPage } from './crm-sync-page';
export { CompliancePage } from './compliance-page';
export { IntegrationsPage } from './integrations-page';
export { LandingFunnelsPage } from './landing-funnels-page';
export { SignupFormsPage } from './signup-forms-page';
export { SignupFormBuilderPage } from './signup-form-builder-page';
export { LandingPagesPage } from './landing-pages-page';
export { LandingPageBuilderPage } from './landing-page-builder-page';
export { PopupsPage } from './popups-page';
export { PopupBuilderPage } from './popup-builder-page';
